name: Firmware Upload

on:
  push:

jobs:
  upload-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: iot123project  # 👈 or use ${{ secrets.GCP_PROJECT_ID }} if you prefer secrets

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload .bin files to GCS
        run: |
          for file in firmware/**/*.bin; do
            echo "Uploading $file to gs://ota-firmware-bucket/firmware/"
            gsutil cp "$file" gs://ota-firmware-bucket/firmware/
          done

      - name: Publish Pub/Sub message
        run: |
          for file in firmware/**/*.bin; do
            FILE_NAME=$(basename "$file")
            gcloud pubsub topics publish ota-updates \
              --message="{\"firmware\":\"$FILE_NAME\",\"timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}"
          done
