name: Firmware Upload

on:
  push:
    paths:
      - 'firmware/**/*.bin'

jobs:
  upload-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload .bin files to GCS
        env:
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        run: |
          for file in firmware/**/*.bin; do
            echo "Uploading $file to gs://$GCS_BUCKET_NAME/firmware/"
            gsutil cp "$file" "gs://$GCS_BUCKET_NAME/firmware/"
          done

      - name: Publish Pub/Sub message
        run: |
          for file in firmware/**/*.bin; do
            FILE_NAME=$(basename "$file")
            gcloud pubsub topics publish ota-updates \
              --message="{\"firmware\":\"$FILE_NAME\",\"timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}"
          done
